from typing import List, Tuple, Union
from mynumpy.dtypes import Numbers


class ndarray:
    def __init__(data: List[Numbers]): ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __eq__(self, other: ndarray) -> bool: ...

    def  __ne__(self, other: ndarray) -> bool: ...

    def __add__(self, other: Union[Numbers, ndarray]) -> ndarray: ...

    def __sub__(self, other: Union[Numbers, ndarray]) -> ndarray: ...

    def __mul__(self, other: Union[Numbers, ndarray]) -> ndarray: ...

    def __matmul__(self, other: ndarray) -> ndarray: ...

    def __truediv__(self, other: Union[Numbers, ndarray]) -> ndarray: ...

    def __len__(self) -> int: ...

    @property
    def ndim(self) -> int: ...

    @property
    def shape(self) -> Tuple[int, ...]: ...

    @property
    def size(self) -> int: ...

    @property
    def T(self) -> ndarray: ...

    def flatten(self) -> ndarray: ...

    def reshape(self, shape: Union[int, List[int], Tuple[int]], *args) -> ndarray: ...


def count_dims(data: list, dims: list) -> list: ...


def calc_size(shape: Union[int, List[int], Tuple[int]], *args) -> int: ...


def zeros(shape: Union[int, List[int], Tuple[int]]) -> ndarray: ...


def zeros_like(a: Union[list, ndarray]) -> ndarray: ...
