from typing import List, Union
from mynumpy.dtypes import Numbers

class ndarray:
    def __init__(data: List[Numbers]): ...

    def __add__(self, other: Union[Numbers, ndarray]): ...

    def __sub__(self, other: Union[Numbers, ndarray]): ...

    def __mul__(self, other: Union[Numbers, ndarray]): ...

    def __truediv__(self, other: Union[Numbers, ndarray]): ...
